version: "3"
services:
  ardupilot:
    image: brzozia/ardupilot-solarplane:latest
    environment: 
      DISPLAY: "192.168.1.32:0.0"
    volumes:
      - ./:/ardupilot
    stdin_open: true
    tty: true
  ardupilot-unix:
    image: brzozia/ardupilot-solarplane:latest
    environment: 
      - DISPLAY=${DISPLAY}
    volumes:
      - ./:/ardupilot
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true

